# Generated by Django 5.0.5 on 2024-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=20)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada')], max_length=20)),
                ('hobbies', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
